version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: ./sample-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./sample-app:/app
      - /app/node_modules
    depends_on:
      - backend
